apiVersion: batch/v1
kind: Job
metadata:
  name: dockefilesearchjob
spec:
  template:
    spec:
      containers:
      - name: dockerfiletoolcont
        image: avelarana/rhchallenge:1.0
        env:
        - name: REPOSITORY_LIST_URL
          value: "https://gist.githubusercontent.com/jmelis/c60e61a893248244dc4fa12b946585c4/raw/25d39f67f2405330a6314cad64fac423a171162c/sources.txt"
      restartPolicy: OnFailure
  backoffLimit: 4
